#!/bin/bash

scapi server.Server 8885 socketParties0.properties &
scapi server.Server 8886 socketParties1.properties &
scapi server.Server 8887 socketParties2.properties &
scapi server.Server 8888 socketParties3.properties &
scapi server.Server 8889 socketParties4.properties &