#!/bin/bash

scapi main socketParties0.properties &
scapi main socketParties1.properties &
scapi main socketParties2.properties &
scapi main socketParties3.properties &
scapi main socketParties4.properties &