#!/bin/bash

classpath=../assets/Scapi-2.4.jar::../assets/commons-exec-1.2.jar:../assets/bcprov-jdk16-146.jar:../lib/hamcrest-core-1.3.jar:../scapi/assets/activemq-all-5.9.1.jar:../lib/jpbc-api-2.0.0.jar:../lib/jpbc-plaf-2.0.0.jar
lib_path=../assets/:/usr/ssl/lib/
export LD_LIBRARY_PATH=/usr/ssl/lib:../assets

java -classpath $classpath -Djava.library.path=$lib_path pederson.Test socketProps0 >/tmp/p0 &
java -classpath $classpath -Djava.library.path=$lib_path pederson.Test socketProps1 >/tmp/p1 &
java -classpath $classpath -Djava.library.path=$lib_path pederson.Test socketProps2 >/tmp/p2 &

